<#
.SYNOPSIS
  Install Caddy as HTTPS reverse proxy for ATsoftERP.

.DESCRIPTION
  Installs Caddy via Chocolatey (or manual download), generates a self-signed
  TLS certificate for local use, and configures Caddy to:
    - Terminate TLS on port 443
    - Reverse-proxy /api/* and /api/* to localhost:4000 (API)
    - Reverse-proxy everything else to localhost:3000 (Web)

  MUST be run as Administrator.

.PARAMETER Hostname
  The hostname for the TLS certificate. Defaults to the machine's hostname.
  Use the machine's LAN IP for LAN access.

.PARAMETER DryRun
  Show what would be done without making changes.
#>
param(
  [string]$Hostname = "",
  [switch]$DryRun
)

$ErrorActionPreference = "Stop"

# --- Admin check ---
$isAdmin = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
if (-not $isAdmin) {
  Write-Host "ERROR: This script must be run as Administrator." -ForegroundColor Red
  exit 1
}

# --- Determine hostname ---
if (-not $Hostname) {
  $Hostname = $env:COMPUTERNAME
  Write-Host "No hostname specified. Using machine name: $Hostname" -ForegroundColor Yellow
}

Write-Host "=== ATsoftERP HTTPS Reverse Proxy Installer ===" -ForegroundColor Cyan
Write-Host "Hostname: $Hostname"
Write-Host ""

# --- Step 1: Install Caddy ---
$caddyPath = Get-Command caddy -ErrorAction SilentlyContinue
if (-not $caddyPath) {
  Write-Host "--- Installing Caddy ---" -ForegroundColor Yellow

  $choco = Get-Command choco -ErrorAction SilentlyContinue
  $winget = Get-Command winget -ErrorAction SilentlyContinue

  if ($DryRun) {
    Write-Host "  [DRY-RUN] Would install Caddy via Chocolatey or winget" -ForegroundColor Gray
  } elseif ($choco) {
    Write-Host "  Installing via Chocolatey..." -ForegroundColor Cyan
    & choco install caddy -y
    if ($LASTEXITCODE -ne 0) {
      Write-Host "  ERROR: Chocolatey install failed." -ForegroundColor Red
      Write-Host "  Try manual install: https://caddyserver.com/docs/install" -ForegroundColor Yellow
      exit 1
    }
    # Refresh PATH
    $env:Path = [System.Environment]::GetEnvironmentVariable("Path", "Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path", "User")
    $caddyPath = Get-Command caddy -ErrorAction SilentlyContinue
  } elseif ($winget) {
    Write-Host "  Installing via winget..." -ForegroundColor Cyan
    & winget install Caddy.Caddy --accept-package-agreements --accept-source-agreements
    $env:Path = [System.Environment]::GetEnvironmentVariable("Path", "Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path", "User")
    $caddyPath = Get-Command caddy -ErrorAction SilentlyContinue
  } else {
    Write-Host "  ERROR: Neither Chocolatey nor winget found." -ForegroundColor Red
    Write-Host "  Install Caddy manually: https://caddyserver.com/docs/install" -ForegroundColor Yellow
    exit 1
  }

  if (-not $caddyPath) {
    Write-Host "  ERROR: Caddy installed but not found in PATH after install." -ForegroundColor Red
    Write-Host "  Try restarting your terminal or adding Caddy to PATH manually." -ForegroundColor Yellow
    exit 1
  }
  Write-Host "  Caddy installed: $($caddyPath.Source)" -ForegroundColor Green
} else {
  Write-Host "Caddy already installed: $($caddyPath.Source)" -ForegroundColor Green
}

# --- Step 2: Create Caddyfile ---
$caddyDir = "C:\ATsoftERP\Config"
if (-not (Test-Path $caddyDir)) {
  if (-not $DryRun) { New-Item -ItemType Directory -Path $caddyDir -Force | Out-Null }
}

$caddyfilePath = Join-Path $caddyDir "Caddyfile"

# Get all IPs for SAN certificate
$localIPs = Get-NetIPAddress -AddressFamily IPv4 | Where-Object { $_.IPAddress -ne "127.0.0.1" -and $_.IPAddress -notlike "169.*" } | Select-Object -ExpandProperty IPAddress
$sanList = @($Hostname) + $localIPs | Where-Object { $_ } | Sort-Object -Unique

# Build the TLS block - use self-signed for local
$tlsDomains = ($sanList | ForEach-Object { "`"$_`"" }) -join " "

$caddyfile = @"
# ATsoftERP Caddyfile
# Self-signed TLS for local/LAN access
# Generated by install-caddy-https.ps1 on $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

{
  # Use internal PKI for self-signed certs (no ACME needed for local)
  # Logs
  log {
    output file C:\ATsoftERP\Logs\caddy-access.log {
      roll_size 50mb
      roll_keep 10
    }
  }
}

# Main site: HTTPS termination
https://{$Hostname} {
  tls internal

  # API endpoints -> port 4000
  handle_path /api/* {
    reverse_proxy localhost:4000
  }

  # All other requests -> port 3000 (Next.js)
  handle {
    reverse_proxy localhost:3000
  }

  # Security headers
  header {
    X-Content-Type-Options nosniff
    X-Frame-Options DENY
    Referrer-Policy strict-origin-when-cross-origin
    -Server
  }

  # Compression
  encode gzip zstd
}
"@

if ($DryRun) {
  Write-Host ""
  Write-Host "[DRY-RUN] Would write Caddyfile to: $caddyfilePath" -ForegroundColor Gray
  Write-Host "Content:" -ForegroundColor Gray
  Write-Host $caddyfile -ForegroundColor DarkGray
} else {
  $caddyfile | Set-Content -Path $caddyfilePath -Encoding UTF8 -Force
  Write-Host "Caddyfile written: $caddyfilePath" -ForegroundColor Green
}

# --- Step 3: Stop existing Caddy if running ---
$existingCaddy = Get-Process caddy -ErrorAction SilentlyContinue
if ($existingCaddy) {
  if ($DryRun) {
    Write-Host "[DRY-RUN] Would stop existing Caddy process" -ForegroundColor Gray
  } else {
    Write-Host "Stopping existing Caddy process..." -ForegroundColor Yellow
    Stop-Process -Name caddy -Force -ErrorAction SilentlyContinue
    Start-Sleep -Seconds 2
  }
}

# --- Step 4: Start Caddy ---
if ($DryRun) {
  Write-Host "[DRY-RUN] Would start Caddy with: caddy run --config $caddyfilePath" -ForegroundColor Gray
} else {
  Write-Host "Starting Caddy..." -ForegroundColor Cyan

  # Start Caddy as a background process (it runs in foreground, so we use Start-Process)
  $caddyExe = $caddyPath.Source
  Start-Process -FilePath $caddyExe -ArgumentList "run", "--config", $caddyfilePath `
    -WindowStyle Hidden -PassThru | Out-Null

  Start-Sleep -Seconds 3

  # Verify it's running
  $caddyProcess = Get-Process caddy -ErrorAction SilentlyContinue
  if ($caddyProcess) {
    Write-Host "Caddy running (PID: $($caddyProcess.Id))" -ForegroundColor Green
  } else {
    Write-Host "WARNING: Caddy process not found after start. Check logs." -ForegroundColor Yellow
  }
}

# --- Step 5: Create Caddy Windows service (optional) ---
Write-Host ""
Write-Host "--- Installing Caddy as Windows Service ---" -ForegroundColor Yellow

if ($DryRun) {
  Write-Host "[DRY-RUN] Would install Caddy as 'ATsoftERP_Caddy' service via NSSM" -ForegroundColor Gray
} else {
  $nssmPath = "C:\nssm-2.24\win64\nssm.exe"
  if (Test-Path $nssmPath) {
    # Remove existing service if present
    $existingSvc = & sc.exe query ATsoftERP_Caddy 2>&1
    if ($LASTEXITCODE -eq 0) {
      & net stop ATsoftERP_Caddy 2>&1 | Out-Null
      & sc.exe delete ATsoftERP_Caddy 2>&1 | Out-Null
      Start-Sleep -Seconds 2
    }

    & $nssmPath install ATsoftERP_Caddy $caddyPath.Source "run", "--config", $caddyfilePath
    & $nssmPath set ATsoftERP_Caddy DisplayName "ATsoftERP HTTPS Proxy (Caddy)"
    & $nssmPath set ATsoftERP_Caddy Description "HTTPS reverse proxy for ATsoft ERP"
    & $nssmPath set ATsoftERP_Caddy Start SERVICE_AUTO_START
    & $nssmPath set ATsoftERP_Caddy AppDirectory "C:\ATsoftERP\Config"
    & $nssmPath set ATsoftERP_Caddy AppStdout "C:\ATsoftERP\Logs\ATsoftERP_Caddy.stdout.log"
    & $nssmPath set ATsoftERP_Caddy AppStderr "C:\ATsoftERP\Logs\ATsoftERP_Caddy.stderr.log"
    & $nssmPath set ATsoftERP_Caddy AppRotateFiles 1
    & $nssmPath set ATsoftERP_Caddy AppRotateBytes 52428800
    & sc.exe failure ATsoftERP_Caddy reset= 86400 actions= restart/5000/restart/10000/restart/30000 | Out-Null

    # Stop the manual process (service will take over)
    Stop-Process -Name caddy -Force -ErrorAction SilentlyContinue
    Start-Sleep -Seconds 2

    Start-Service ATsoftERP_Caddy
    Start-Sleep -Seconds 3

    $svcStatus = Get-Service ATsoftERP_Caddy -ErrorAction SilentlyContinue
    if ($svcStatus -and $svcStatus.Status -eq "Running") {
      Write-Host "Caddy service installed and running." -ForegroundColor Green
    } else {
      Write-Host "WARNING: Caddy service may not be running. Check: Get-Service ATsoftERP_Caddy" -ForegroundColor Yellow
    }
  } else {
    Write-Host "  NSSM not found. Caddy running as manual process only." -ForegroundColor Yellow
    Write-Host "  Install NSSM for service management: choco install nssm -y" -ForegroundColor Gray
  }
}

# --- Step 6: Open firewall port 443 ---
Write-Host ""
Write-Host "--- Configuring Windows Firewall ---" -ForegroundColor Yellow

if ($DryRun) {
  Write-Host "[DRY-RUN] Would add firewall rule for port 443 (HTTPS)" -ForegroundColor Gray
} else {
  $existingRule = Get-NetFirewallRule -DisplayName "ATsoftERP HTTPS (443)" -ErrorAction SilentlyContinue
  if (-not $existingRule) {
    New-NetFirewallRule -DisplayName "ATsoftERP HTTPS (443)" `
      -Direction Inbound -Protocol TCP -LocalPort 443 `
      -Action Allow -Profile Private -Enabled True | Out-Null
    Write-Host "Firewall rule added for port 443." -ForegroundColor Green
  } else {
    Write-Host "Firewall rule already exists." -ForegroundColor Green
  }
}

# --- Step 7: Verify HTTPS ---
Write-Host ""
Write-Host "=== HTTPS Verification ===" -ForegroundColor Cyan

if ($DryRun) {
  Write-Host "[DRY-RUN] Would verify HTTPS at https://$Hostname" -ForegroundColor Gray
} else {
  # Ignore self-signed cert error for verification
  [System.Net.ServicePointManager]::ServerCertificateValidationCallback = { $true }

  Write-Host "Testing HTTPS on port 443..." -ForegroundColor Cyan
  try {
    $httpsResponse = Invoke-WebRequest -Uri "https://localhost" -TimeoutSec 10 -UseBasicParsing -SkipCertificateCheck
    Write-Host "HTTPS: $($httpsResponse.StatusCode)" -ForegroundColor Green
  } catch {
    Write-Host "HTTPS test: $($_.Exception.Message)" -ForegroundColor Yellow
    Write-Host "This may be expected if Caddy is using a self-signed cert." -ForegroundColor Gray
  }

  try {
    $apiHttps = Invoke-WebRequest -Uri "https://localhost/api/v1/health" -TimeoutSec 10 -UseBasicParsing -SkipCertificateCheck
    Write-Host "API via HTTPS: $($apiHttps.StatusCode)" -ForegroundColor Green
  } catch {
    Write-Host "API HTTPS: $($_.Exception.Message)" -ForegroundColor Yellow
  }

  try {
    $webHttps = Invoke-WebRequest -Uri "https://localhost:3000" -TimeoutSec 10 -UseBasicParsing -SkipCertificateCheck
    Write-Host "Web direct: $($webHttps.StatusCode)" -ForegroundColor Green
  } catch {
    Write-Host "Web direct: $($_.Exception.Message)" -ForegroundColor Yellow
  }
}

# --- Summary ---
Write-Host ""
Write-Host "=== Summary ===" -ForegroundColor Cyan
Write-Host "Caddyfile   : $caddyfilePath"
Write-Host "HTTPS URL   : https://$Hostname"
Write-Host "API (direct): http://localhost:4000"
Write-Host "Web (direct): http://localhost:3000"
Write-Host ""
Write-Host "Logs        : C:\ATsoftERP\Logs\caddy-access.log"
Write-Host "Service     : ATsoftERP_Caddy (auto-start)"
Write-Host ""
Write-Host "To edit: edit $caddyfilePath and restart the service."
Write-Host "  Restart-Service ATsoftERP_Caddy"
Write-Host "Done." -ForegroundColor Green
