/**
 * R4P TASK 4 / TASK 5: canonical duplicate prevention for the spare-parts domain.
 *
 * WHY THIS FILE EXISTS. The canonical business rule of this stage is
 *
 *     "One technically identical spare part = one canonical SparePart item."
 *
 * Before R4P, SparePartsService.create() compared nothing except the generated
 * `code`. Because the code is auto-generated by NumberingService, two operators
 * who each typed "Bearing SKF 6205" produced two different codes and therefore
 * two rows for one physically identical bearing. Nothing in the write path could
 * detect that. This module is the evidence-based identity comparison that the
 * write path was missing.
 *
 * WHAT IS DELIBERATELY NOT PROOF. The stage specification forbids using any of
 * the following as evidence of technical equivalence, and this resolver refuses
 * to treat them as identity:
 *
 *   - the item name, in Arabic or English (SPARE_PART_NAME_FORBIDDEN)
 *   - quantity, minStock, maxStock, reorderPoint
 *   - machine, machine code, production line, warehouse, storage location
 *   - usage notes, descriptions, categories applied loosely
 *
 * A name is only ever used as a human-readable echo of a verdict that was
 * already reached on stronger evidence. Treating "same name" as "same part" is
 * exactly the failure mode this stage exists to prevent.
 *
 * IDENTITY LADDER (strongest first, per the stage specification). The resolver
 * returns the FIRST rung that yields at least one candidate, and reports which
 * rung decided the outcome:
 *
 *   MANUFACTURER_PART_NUMBER   manufacturer + partNumber   strongest
 *   PART_NUMBER               partNumber                  (no manufacturer required)
 *   PRODUCT_IDENTITY          productId                   verified product link
 *   MANUFACTURER_MODEL_SPEC    manufacturer + model + specification
 *   SPECIFICATION_SET         specification
 *
 * A rung that cannot be evaluated because the required fields are missing is
 * skipped rather than downgraded, so an item with no manufacturer number is
 * never judged by a weaker rung just because a weaker field happened to be
 * filled in.
 */

export type SparePartIdentityField =
  | 'manufacturer'
  | 'partNumber'
  | 'productId'
  | 'model'
  | 'specification';

export const SPARE_PART_IDENTITY_LADDER: readonly SparePartIdentityField[][] = [
  ['manufacturer', 'partNumber'],
  ['partNumber'],
  ['productId'],
  ['manufacturer', 'model', 'specification'],
  ['specification'],
];

export const CANONICAL_VERDICT_UNIQUE = 'CANONICAL_IDENTITY_UNIQUE';
export const CANONICAL_VERDICT_EXACT_DUPLICATE = 'CANONICAL_IDENTITY_EXACT_DUPLICATE';
export const CANONICAL_VERDICT_REVIEW_REQUIRED = 'CANONICAL_IDENTITY_REVIEW_REQUIRED';

export interface CanonicalIdentityInput {
  code?: string | null;
  name?: string | null;
  manufacturer?: string | null;
  partNumber?: string | null;
  productId?: string | null;
  model?: string | null;
  specification?: string | null;
  quantity?: number | null;
  minStock?: number | null;
  maxStock?: number | null;
  reorderPoint?: number | null;
}

export interface CanonicalIdentityCandidate {
  id: string;
  code?: string | null;
  name?: string | null;
  manufacturer?: string | null;
  partNumber?: string | null;
  productId?: string | null;
  model?: string | null;
  specification?: string | null;
}

export interface CanonicalIdentityDecision {
  verdict: typeof CANONICAL_VERDICT_UNIQUE | typeof CANONICAL_VERDICT_EXACT_DUPLICATE | typeof CANONICAL_VERDICT_REVIEW_REQUIRED;
  /** The identity rung that decided this outcome, or null when nothing was comparable. */
  basis: readonly SparePartIdentityField[] | null;
  basisLabel: string | null;
  /** Existing rows that already represent this technical identity. */
  matches: CanonicalIdentityCandidate[];
  /** Human-readable explanation, safe to place in an audit detail or a 409 body. */
  reason: string;
}

const BASIS_LABELS: Record<string, string> = {
  'manufacturer+partNumber': 'MANUFACTURER_PART_NUMBER',
  partNumber: 'PART_NUMBER',
  productId: 'PRODUCT_IDENTITY',
  'manufacturer+model+specification': 'MANUFACTURER_MODEL_SPEC',
  specification: 'SPECIFICATION_SET',
};

/**
 * Normalises a value for identity comparison.
 *
 * Trim and case folding only. No fuzzy matching, no whitespace collapsing inside
 * punctuation, and deliberately no Arabic normalisation: two strings that differ
 * in a diacritic are treated as different, because treating them as equal would
 * be a guess, and the stage forbids inferring equivalence from names.
 */
function normalize(value: string | null | undefined): string | null {
  if (value === null || value === undefined) return null;
  const trimmed = String(value).trim();
  if (trimmed.length === 0) return null;
  return trimmed.toLocaleLowerCase();
}

/**
 * Returns true when every field of the rung carries a usable normalized value on
 * BOTH the incoming item and the candidate. A rung is only comparable when it is
 * complete; a partially filled rung is not evidence.
 */
function rungMatches(
  rung: readonly SparePartIdentityField[],
  input: Record<SparePartIdentityField, string | null>,
  candidate: Record<SparePartIdentityField, string | null>,
): boolean {
  return rung.every((field) => input[field] !== null && candidate[field] !== null && input[field] === candidate[field]);
}

function basisKey(rung: readonly SparePartIdentityField[]): string {
  return rung.join('+');
}

/**
 * Evaluates the incoming identity against the existing canonical catalog.
 *
 * `candidates` must already be restricted by the caller to the rows that are
 * comparable, i.e. non-deleted rows. The resolver itself performs no database
 * access, which keeps the ladder deterministic and directly unit-testable.
 *
 * Contract:
 *   - zero comparable rungs           -> UNIQUE (nothing can be proven either way)
 *   - strongest comparable rung, 1 hit -> EXACT_DUPLICATE (reuse the existing row)
 *   - strongest comparable rung, >1 hit -> REVIEW_REQUIRED (never choose arbitrarily)
 *
 * The caller is responsible for turning EXACT_DUPLICATE and REVIEW_REQUIRED into
 * a rejection. This function never mutates anything.
 */
export function evaluateSparePartCanonicalIdentity(
  input: CanonicalIdentityInput,
  candidates: readonly CanonicalIdentityCandidate[],
): CanonicalIdentityDecision {
  const normalizedInput: Record<SparePartIdentityField, string | null> = {
    manufacturer: normalize(input.manufacturer),
    partNumber: normalize(input.partNumber),
    productId: normalize(input.productId),
    model: normalize(input.model),
    specification: normalize(input.specification),
  };

  for (const rung of SPARE_PART_IDENTITY_LADDER) {
    const key = basisKey(rung);
    const label = BASIS_LABELS[key];

    const comparable = candidates.filter((candidate) =>
      rung.every((field) => normalizedInput[field] !== null && normalize(candidate[field]) !== null),
    );
    if (comparable.length === 0) continue;

    const matches = comparable.filter((candidate) =>
      rungMatches(
        rung,
        normalizedInput,
        {
          manufacturer: normalize(candidate.manufacturer),
          partNumber: normalize(candidate.partNumber),
          productId: normalize(candidate.productId),
          model: normalize(candidate.model),
          specification: normalize(candidate.specification),
        },
      ),
    );

    if (matches.length === 0) {
      // The strongest comparable rung is decisive and found nothing. We must NOT
      // fall through to a weaker rung, because that would let a part number
      // mismatch be excused by a matching free-text specification.
      return {
        verdict: CANONICAL_VERDICT_UNIQUE,
        basis: rung,
        basisLabel: label,
        matches: [],
        reason: `No existing canonical spare part shares this ${label} identity.`,
      };
    }

    if (matches.length === 1) {
      const only = matches[0];
      return {
        verdict: CANONICAL_VERDICT_EXACT_DUPLICATE,
        basis: rung,
        basisLabel: label,
        matches,
        reason: `An existing canonical spare part already represents this ${label} identity (${only.code ?? only.id}). Reuse it instead of creating a duplicate.`,
      };
    }

    return {
      verdict: CANONICAL_VERDICT_REVIEW_REQUIRED,
      basis: rung,
      basisLabel: label,
      matches,
      reason: `${matches.length} existing canonical spare parts share this ${label} identity (${matches
        .map((m) => m.code ?? m.id)
        .join(', ')}). Review and select the correct existing item; no item was chosen automatically.`,
    };
  }

  return {
    verdict: CANONICAL_VERDICT_UNIQUE,
    basis: null,
    basisLabel: null,
    matches: [],
    reason:
      'No manufacturer part number, product link, or specification is available, so technical equivalence cannot be proven. The item name was deliberately not used as identity.',
  };
}