export const CMMS_EXTRA_PERMISSIONS: { key: string; module: string; action: string }[] = [
  // machine-category
  { key: "machine-category:delete", module: "machine-category", action: "delete" },
  { key: "machine-category:activate", module: "machine-category", action: "activate" },
  { key: "machine-category:deactivate", module: "machine-category", action: "deactivate" },
  { key: "machine-category:summary", module: "machine-category", action: "summary" },
  { key: "machine-category:machines", module: "machine-category", action: "machines" },
  // machine-part
  { key: "machine-part:delete", module: "machine-part", action: "delete" },
  { key: "machine-part:activate", module: "machine-part", action: "activate" },
  { key: "machine-part:deactivate", module: "machine-part", action: "deactivate" },
  { key: "machine-part:linkMachine", module: "machine-part", action: "linkMachine" },
  { key: "machine-part:unlinkMachine", module: "machine-part", action: "unlinkMachine" },
  // machine-document (new module, all actions)
  { key: "machine-document:create", module: "machine-document", action: "create" },
  { key: "machine-document:read", module: "machine-document", action: "read" },
  { key: "machine-document:update", module: "machine-document", action: "update" },
  { key: "machine-document:deactivate", module: "machine-document", action: "deactivate" },
  { key: "machine-document:download", module: "machine-document", action: "download" },
  { key: "machine-document:history", module: "machine-document", action: "history" },
  // machine (PATCH/POST/DELETE actions)
  { key: "machine:updateStatus", module: "machine", action: "updateStatus" },
  { key: "machine:updateLocation", module: "machine", action: "updateLocation" },
  { key: "machine:updateManufacturer", module: "machine", action: "updateManufacturer" },
  { key: "machine:updateWarranty", module: "machine", action: "updateWarranty" },
  { key: "machine:updateImage", module: "machine", action: "updateImage" },
  // maintenance-request
  { key: "maintenance-request:start", module: "maintenance-request", action: "start" },
  { key: "maintenance-request:complete", module: "maintenance-request", action: "complete" },
  { key: "maintenance-request:cancel", module: "maintenance-request", action: "cancel" },
  { key: "maintenance-request:assign", module: "maintenance-request", action: "assign" },
  // maintenance-request-part (new module, all actions)
  { key: "maintenance-request-part:create", module: "maintenance-request-part", action: "create" },
  { key: "maintenance-request-part:read", module: "maintenance-request-part", action: "read" },
  { key: "maintenance-request-part:update", module: "maintenance-request-part", action: "update" },
  { key: "maintenance-request-part:delete", module: "maintenance-request-part", action: "delete" },
  // maintenance-request-cost (new module, all actions)
  { key: "maintenance-request-cost:create", module: "maintenance-request-cost", action: "create" },
  { key: "maintenance-request-cost:read", module: "maintenance-request-cost", action: "read" },
  { key: "maintenance-request-cost:update", module: "maintenance-request-cost", action: "update" },
  { key: "maintenance-request-cost:delete", module: "maintenance-request-cost", action: "delete" },
  // maintenance-checklist-execution (new module)
  { key: "maintenance-checklist-execution:create", module: "maintenance-checklist-execution", action: "create" },
  { key: "maintenance-checklist-execution:read", module: "maintenance-checklist-execution", action: "read" },
  { key: "maintenance-checklist-execution:update", module: "maintenance-checklist-execution", action: "update" },
  { key: "maintenance-checklist-execution:complete", module: "maintenance-checklist-execution", action: "complete" },
  // maintenance-task
  { key: "maintenance-task:start", module: "maintenance-task", action: "start" },
  { key: "maintenance-task:complete", module: "maintenance-task", action: "complete" },
  { key: "maintenance-task:cancel", module: "maintenance-task", action: "cancel" },
  // maintenance-schedule
  { key: "maintenance-schedule:activate", module: "maintenance-schedule", action: "activate" },
  { key: "maintenance-schedule:deactivate", module: "maintenance-schedule", action: "deactivate" },
  // maintenance-checklist
  { key: "maintenance-checklist:activate", module: "maintenance-checklist", action: "activate" },
  { key: "maintenance-checklist:deactivate", module: "maintenance-checklist", action: "deactivate" },
  // downtime-log (new module, all actions)
  { key: "downtime-log:create", module: "downtime-log", action: "create" },
  { key: "downtime-log:read", module: "downtime-log", action: "read" },
  { key: "downtime-log:update", module: "downtime-log", action: "update" },
  { key: "downtime-log:delete", module: "downtime-log", action: "delete" },
  { key: "downtime-log:close", module: "downtime-log", action: "close" },
  { key: "downtime-log:cancel", module: "downtime-log", action: "cancel" },
  // maintenance-dashboard (Batch 31)
  { key: "maintenance-dashboard:summary", module: "maintenance-dashboard", action: "summary" },
  { key: "maintenance-dashboard:openRequests", module: "maintenance-dashboard", action: "openRequests" },
  { key: "maintenance-dashboard:overdueTasks", module: "maintenance-dashboard", action: "overdueTasks" },
  { key: "maintenance-dashboard:upcomingPM", module: "maintenance-dashboard", action: "upcomingPM" },
  { key: "maintenance-dashboard:currentDowntime", module: "maintenance-dashboard", action: "currentDowntime" },
  { key: "maintenance-dashboard:recentActivity", module: "maintenance-dashboard", action: "recentActivity" },
  { key: "maintenance-dashboard:costSummary", module: "maintenance-dashboard", action: "costSummary" },
  { key: "maintenance-dashboard:partsUsage", module: "maintenance-dashboard", action: "partsUsage" },
  // maintenance-request extensions (Batch 31)
  { key: "maintenance-request:reopen", module: "maintenance-request", action: "reopen" },
  { key: "maintenance-request:close", module: "maintenance-request", action: "close" },
  { key: "maintenance-request:workflow", module: "maintenance-request", action: "workflow" },
  { key: "maintenance-request:activity.view", module: "maintenance-request", action: "activity.view" },
  { key: "maintenance-request:attachments.view", module: "maintenance-request", action: "attachments.view" },
  { key: "maintenance-request:print", module: "maintenance-request", action: "print" },
  // installed-parts (critical permission alignment)
  { key: "installed-parts:read", module: "installed-parts", action: "read" },
  { key: "maintenance-request:checklist.view", module: "maintenance-request", action: "checklist.view" },
  { key: "maintenance-request:checklist.manage", module: "maintenance-request", action: "checklist.manage" },
  { key: "maintenance-request:summary", module: "maintenance-request", action: "summary" },
  { key: "maintenance-request:createEmergency", module: "maintenance-request", action: "createEmergency" },
  // maintenance-request-required-part (Batch F)
  { key: "maintenance-request-required-part:read", module: "maintenance-request-required-part", action: "read" },
  { key: "maintenance-request-required-part:create", module: "maintenance-request-required-part", action: "create" },
  { key: "maintenance-request-required-part:update", module: "maintenance-request-required-part", action: "update" },
  { key: "maintenance-request-required-part:cancel", module: "maintenance-request-required-part", action: "cancel" },
  // maintenance-task extensions (Batch 31)
  { key: "maintenance-task:assign", module: "maintenance-task", action: "assign" },
  { key: "maintenance-task:myTasks", module: "maintenance-task", action: "myTasks" },
  { key: "maintenance-task:byRequest", module: "maintenance-task", action: "byRequest" },
  { key: "maintenance-task:overdue", module: "maintenance-task", action: "overdue" },
  // maintenance-schedule extensions (Batch 31)
  { key: "maintenance-schedule:execute", module: "maintenance-schedule", action: "execute" },
  { key: "maintenance-schedule:history", module: "maintenance-schedule", action: "history" },
  { key: "maintenance-schedule:generateRequest", module: "maintenance-schedule", action: "generateRequest" },
  // preventive-maintenance (Batch 31)
  { key: "preventive-maintenance:upcoming", module: "preventive-maintenance", action: "upcoming" },
  { key: "preventive-maintenance:overdue", module: "preventive-maintenance", action: "overdue" },
  { key: "preventive-maintenance:calendar", module: "preventive-maintenance", action: "calendar" },
  { key: "preventive-maintenance:executionHistory", module: "preventive-maintenance", action: "executionHistory" },
  { key: "preventive-maintenance:generateDueTasks", module: "preventive-maintenance", action: "generateDueTasks" },
  // downtime-log extensions (Batch 31)
  { key: "downtime-log:startDowntime", module: "downtime-log", action: "startDowntime" },
  { key: "downtime-log:endDowntime", module: "downtime-log", action: "endDowntime" },
  { key: "downtime-log:classify", module: "downtime-log", action: "classify" },
  { key: "downtime-log:current", module: "downtime-log", action: "current" },
  { key: "downtime-log:analysis", module: "downtime-log", action: "analysis" },
  { key: "downtime-log:byMachine", module: "downtime-log", action: "byMachine" },
  { key: "downtime-log:logSummary", module: "downtime-log", action: "logSummary" },
  // downtime-log controller-enforced keys (aligned with downtime-logs.controller.ts)
  { key: "downtime-log:start", module: "downtime-log", action: "start" },
  { key: "downtime-log:end", module: "downtime-log", action: "end" },
  { key: "downtime-log:current.view", module: "downtime-log", action: "current.view" },
  { key: "downtime-log:analysis.view", module: "downtime-log", action: "analysis.view" },
  { key: "downtime-log:byMachine.view", module: "downtime-log", action: "byMachine.view" },
  // machine-component (new module, all actions)
  { key: "machine-component:create", module: "machine-component", action: "create" },
  { key: "machine-component:read", module: "machine-component", action: "read" },
  { key: "machine-component:update", module: "machine-component", action: "update" },
  { key: "machine-component:delete", module: "machine-component", action: "delete" },
  { key: "machine-component:activate", module: "machine-component", action: "activate" },
  { key: "machine-component:deactivate", module: "machine-component", action: "deactivate" },
  // spare-part (new module, all actions)
  { key: "spare-part:create", module: "spare-part", action: "create" },
  { key: "spare-part:read", module: "spare-part", action: "read" },
  { key: "spare-part:update", module: "spare-part", action: "update" },
  { key: "spare-part:delete", module: "spare-part", action: "delete" },
  { key: "spare-part:activate", module: "spare-part", action: "activate" },
  { key: "spare-part:deactivate", module: "spare-part", action: "deactivate" },
  // component-spare-part (new module, all actions)
  { key: "component-spare-part:create", module: "component-spare-part", action: "create" },
  { key: "component-spare-part:read", module: "component-spare-part", action: "read" },
  { key: "component-spare-part:update", module: "component-spare-part", action: "update" },
  { key: "component-spare-part:deactivate", module: "component-spare-part", action: "deactivate" },
  // machine-spare-part (new module, all actions)
  { key: "machine-spare-part:create", module: "machine-spare-part", action: "create" },
  { key: "machine-spare-part:read", module: "machine-spare-part", action: "read" },
  { key: "machine-spare-part:update", module: "machine-spare-part", action: "update" },
  { key: "machine-spare-part:deactivate", module: "machine-spare-part", action: "deactivate" },
  // downtime-rca (new module)
  { key: "downtime-rca:update", module: "downtime-rca", action: "update" },
  { key: "downtime-rca:complete", module: "downtime-rca", action: "complete" },
  // maintenance-reliability (new module)
  { key: "maintenance-reliability:read", module: "maintenance-reliability", action: "read" },
  // maintenance-request-parts workflow (Batch L)
  { key: "maintenance-request-parts:read", module: "maintenance-request-parts", action: "read" },
  { key: "maintenance-request-parts:create", module: "maintenance-request-parts", action: "create" },
  { key: "maintenance-request-parts:update", module: "maintenance-request-parts", action: "update" },
  { key: "maintenance-request-parts:request", module: "maintenance-request-parts", action: "request" },
  { key: "maintenance-request-parts:approve", module: "maintenance-request-parts", action: "approve" },
  { key: "maintenance-request-parts:reject", module: "maintenance-request-parts", action: "reject" },
  { key: "maintenance-request-parts:reserve", module: "maintenance-request-parts", action: "reserve" },
  { key: "maintenance-request-parts:use", module: "maintenance-request-parts", action: "use" },
  { key: "maintenance-request-parts:cancel", module: "maintenance-request-parts", action: "cancel" },
  // maintenance-calendar (Batch N)
  { key: "maintenance-calendar:read", module: "maintenance-calendar", action: "read" },
  { key: "maintenance-calendar:update", module: "maintenance-calendar", action: "update" },
  // maintenance-workload (Batch N)
  { key: "maintenance-workload:read", module: "maintenance-workload", action: "read" },
  { key: "maintenance-workload:manage", module: "maintenance-workload", action: "manage" },
  // maintenance-planning (Batch N)
  { key: "maintenance-planning:read", module: "maintenance-planning", action: "read" },
  { key: "maintenance-planning:update", module: "maintenance-planning", action: "update" },
  { key: "maintenance-planning:assign", module: "maintenance-planning", action: "assign" },
  { key: "maintenance-planning:reschedule", module: "maintenance-planning", action: "reschedule" },
  // maintenance-stock-issue (Batch O)
  { key: "maintenance-stock-issue:create", module: "maintenance-stock-issue", action: "create" },
  { key: "maintenance-stock-issue:read", module: "maintenance-stock-issue", action: "read" },
  // inventory-ledger (Batch P)
  { key: "inventory-ledger:read", module: "inventory-ledger", action: "read" },
  // inventory-reconciliation (Batch P)
  { key: "inventory-reconciliation:read", module: "inventory-reconciliation", action: "read" },
  // opening-balance (Batch Q)
  { key: "inventory:opening-balance:read", module: "inventory:opening-balance", action: "read" },
  { key: "inventory:opening-balance:create", module: "inventory:opening-balance", action: "create" },
  { key: "inventory:opening-balance:update", module: "inventory:opening-balance", action: "update" },
  { key: "inventory:opening-balance:submit", module: "inventory:opening-balance", action: "submit" },
  { key: "inventory:opening-balance:approve", module: "inventory:opening-balance", action: "approve" },
  { key: "inventory:opening-balance:reject", module: "inventory:opening-balance", action: "reject" },
  { key: "inventory:opening-balance:post", module: "inventory:opening-balance", action: "post" },
  { key: "inventory:opening-balance:cancel", module: "inventory:opening-balance", action: "cancel" },
  { key: "inventory:opening-balance:delete-draft", module: "inventory:opening-balance", action: "delete-draft" },
  // stock-adjustment (Batch Q)
  { key: "inventory:stock-adjustment:read", module: "inventory:stock-adjustment", action: "read" },
  { key: "inventory:stock-adjustment:create", module: "inventory:stock-adjustment", action: "create" },
  { key: "inventory:stock-adjustment:update", module: "inventory:stock-adjustment", action: "update" },
  { key: "inventory:stock-adjustment:submit", module: "inventory:stock-adjustment", action: "submit" },
  { key: "inventory:stock-adjustment:approve", module: "inventory:stock-adjustment", action: "approve" },
  { key: "inventory:stock-adjustment:reject", module: "inventory:stock-adjustment", action: "reject" },
  { key: "inventory:stock-adjustment:post", module: "inventory:stock-adjustment", action: "post" },
  { key: "inventory:stock-adjustment:cancel", module: "inventory:stock-adjustment", action: "cancel" },
  { key: "inventory:stock-adjustment:delete-draft", module: "inventory:stock-adjustment", action: "delete-draft" },
  // stock-transfer (Batch R)
  { key: "inventory:stock-transfer:read", module: "inventory:stock-transfer", action: "read" },
  { key: "inventory:stock-transfer:create", module: "inventory:stock-transfer", action: "create" },
  { key: "inventory:stock-transfer:update", module: "inventory:stock-transfer", action: "update" },
  { key: "inventory:stock-transfer:submit", module: "inventory:stock-transfer", action: "submit" },
  { key: "inventory:stock-transfer:approve", module: "inventory:stock-transfer", action: "approve" },
  { key: "inventory:stock-transfer:reject", module: "inventory:stock-transfer", action: "reject" },
  { key: "inventory:stock-transfer:post", module: "inventory:stock-transfer", action: "post" },
  { key: "inventory:stock-transfer:cancel", module: "inventory:stock-transfer", action: "cancel" },
  { key: "inventory:stock-transfer:delete-draft", module: "inventory:stock-transfer", action: "delete-draft" },
  // operational-receipt (Batch S)
  { key: "inventory:operational-receipt:read", module: "inventory:operational-receipt", action: "read" },
  { key: "inventory:operational-receipt:create", module: "inventory:operational-receipt", action: "create" },
  { key: "inventory:operational-receipt:update", module: "inventory:operational-receipt", action: "update" },
  { key: "inventory:operational-receipt:submit", module: "inventory:operational-receipt", action: "submit" },
  { key: "inventory:operational-receipt:approve", module: "inventory:operational-receipt", action: "approve" },
  { key: "inventory:operational-receipt:reject", module: "inventory:operational-receipt", action: "reject" },
  { key: "inventory:operational-receipt:post", module: "inventory:operational-receipt", action: "post" },
  { key: "inventory:operational-receipt:cancel", module: "inventory:operational-receipt", action: "cancel" },
  { key: "inventory:operational-receipt:delete-draft", module: "inventory:operational-receipt", action: "delete-draft" },
];
