'use client';
import React, { useState } from 'react';
import { useRouter } from 'next/navigation';
import { api } from '../../../../../lib/api';
import { useTranslation } from '../../../../../lib/i18n/use-translation';
import { useToast } from '../../../../../components/admin/toast-provider';
import { Button, Input, Card, CardContent } from '../../../../../components/admin/ui';
import { F9Lookup, machineAdapter, productAdapter } from '../../../../../components/f9';
import { useRegisterAdminActions, useStableHandlers, ActionBackIcon, ActionRefreshIcon, ActionSaveIcon, ActionCancelIcon } from '../../../../../components/admin/admin-action-bar';
import { useApiErrorHandler } from '../../../../../components/admin/error-handler';
import { adaptFieldErrorsToMap, focusFirstInvalidField } from '../../../../../lib/form-validation';

export default function CreateMachinePartPage() {
  const { t } = useTranslation();
  const router = useRouter();
  const { showToast } = useToast();
  const handleApiError = useApiErrorHandler();
  const [form, setForm] = useState({
    name: '', partNumber: '', unit: '',
    quantity: 0, minStock: 0,
    machineId: '', productId: '',
  });
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [saving, setSaving] = useState(false);
  const [dirty, setDirty] = useState(false);

  const setField = (field: string, value: any) => {
    setForm(prev => ({ ...prev, [field]: value }));
    setDirty(true);
    if (errors[field]) setErrors(prev => ({ ...prev, [field]: '' }));
  };

  const validate = () => {
    const errs: Record<string, string> = {};
    if (!form.name.trim()) errs.name = t('validation.required');
    if (!form.unit.trim()) errs.unit = t('validation.required');
    if (Number.isNaN(Number(form.quantity)) || Number(form.quantity) < 0) errs.quantity = t('validation.invalidQuantity');
    if (Number.isNaN(Number(form.minStock)) || Number(form.minStock) < 0) errs.minStock = t('validation.invalidQuantity');
    setErrors(errs);
    focusFirstInvalidField(Object.entries(errs).map(([field, message]) => ({ field, code: 'validation.required', message })));
    return Object.keys(errs).length === 0;
  };

  const handleSave = async () => {
    if (!validate()) return;
    setSaving(true);
    try {
      const payload: Record<string, any> = {
        name: form.name.trim(),
        unit: form.unit.trim(),
        quantity: Number(form.quantity),
        minStock: Number(form.minStock),
      };
      if (form.partNumber.trim()) payload.partNumber = form.partNumber.trim();
      if (form.machineId) payload.machineId = form.machineId;
      if (form.productId) payload.productId = form.productId;
      const res = await api.post<{ id: string }>('/maintenance/machine-parts', payload);
      showToast(t('complexForms.recordCreated'), 'success');
      router.push(`/admin/maintenance/machine-parts/${res.id}`);
    } catch (err: any) {
      const config = handleApiError(err);
      if (config.errors?.length) {
        setErrors(adaptFieldErrorsToMap(config.errors));
        focusFirstInvalidField(config.errors);
      }
    } finally { setSaving(false); }
  };

  const { exec } = useStableHandlers({
    back: () => { if (dirty && !confirm(t('complexForms.confirmLeaveUnsaved'))) return; router.back(); },
    refresh: () => { setForm({ name: '', partNumber: '', unit: '', quantity: 0, minStock: 0, machineId: '', productId: '' }); setErrors({}); setDirty(false); },
    save: () => handleSave(),
    cancel: () => { if (dirty && !confirm(t('complexForms.confirmLeaveUnsaved'))) return; router.back(); },
  });

  useRegisterAdminActions([
    { id: 'back', labelKey: 'common.back', icon: <ActionBackIcon />, onClick: () => exec('back') },
    { id: 'refresh', labelKey: 'common.refresh', icon: <ActionRefreshIcon />, onClick: () => exec('refresh') },
    { id: 'save', labelKey: 'actions.save', icon: <ActionSaveIcon />, onClick: () => exec('save'), enabled: !saving },
    { id: 'cancel', labelKey: 'actions.cancel', icon: <ActionCancelIcon />, onClick: () => exec('cancel') },
  ]);

  return (
    <div className="space-y-6">
      <Card>
        <CardContent>
          <div className="space-y-6">
            <h2 className="text-lg font-semibold text-gray-900">{t('complexForms.basicInformation')}</h2>
            <p className="text-sm text-gray-500">{t('common.codeAutoGenerated')}</p>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <Input label={t('maintenance.name')} value={form.name} onChange={(e) => setField('name', e.target.value)} error={errors.name} required />
              <Input label={t('maintenance.partNumber')} value={form.partNumber} onChange={(e) => setField('partNumber', e.target.value)} />
              <Input label={t('maintenance.unit')} value={form.unit} onChange={(e) => setField('unit', e.target.value)} error={errors.unit} required />
              <Input label={t('maintenance.quantity')} type="number" value={String(form.quantity)} onChange={(e) => setField('quantity', e.target.value)} error={errors.quantity} />
              <Input label={t('maintenance.minimumStock')} type="number" value={String(form.minStock)} onChange={(e) => setField('minStock', e.target.value)} error={errors.minStock} />
            </div>
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardContent>
          <h2 className="text-lg font-semibold text-gray-900 mb-4">{t('maintenance.linkedEntities')}</h2>
          <div className="space-y-4">
            <F9Lookup label={t('maintenance.machine')} value={form.machineId} onChange={(v) => setField('machineId', v)} adapter={machineAdapter} />
            <F9Lookup label={t('maintenance.linkedInventoryItem')} value={form.productId} onChange={(v) => setField('productId', v)} adapter={productAdapter} />
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
